/**
 * Fortanix SDKMS REST API
 * This is a set of REST APIs for accessing the Fortanix Self-Defending Key Management System. This includes APIs for managing accounts, and for performing cryptographic and key management operations. 
 *
 * OpenAPI spec version: 1.0.0-20181004
 * Contact: support@fortanix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FortanixSdkmsRestApi);
  }
}(this, function(expect, FortanixSdkmsRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FortanixSdkmsRestApi.App();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('App', function() {
    it('should create an instance of App', function() {
      // uncomment below and update the code to test App
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be.a(FortanixSdkmsRestApi.App);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property appId (base name: "app_id")', function() {
      // uncomment below and update the code to test the property appId
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property authType (base name: "auth_type")', function() {
      // uncomment below and update the code to test the property authType
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property _interface (base name: "interface")', function() {
      // uncomment below and update the code to test the property _interface
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property acctId (base name: "acct_id")', function() {
      // uncomment below and update the code to test the property acctId
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property groups (base name: "groups")', function() {
      // uncomment below and update the code to test the property groups
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property defaultGroup (base name: "default_group")', function() {
      // uncomment below and update the code to test the property defaultGroup
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property appType (base name: "app_type")', function() {
      // uncomment below and update the code to test the property appType
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property regions (base name: "regions")', function() {
      // uncomment below and update the code to test the property regions
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property creator (base name: "creator")', function() {
      // uncomment below and update the code to test the property creator
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

    it('should have the property lastusedAt (base name: "lastused_at")', function() {
      // uncomment below and update the code to test the property lastusedAt
      //var instane = new FortanixSdkmsRestApi.App();
      //expect(instance).to.be();
    });

  });

}));
