/**
 * Fortanix SDKMS REST API
 * This is a set of REST APIs for accessing the Fortanix Self-Defending Key Management System. This includes APIs for managing accounts, and for performing cryptographic and key management operations. 
 *
 * OpenAPI spec version: 1.0.0-20181004
 * Contact: support@fortanix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FortanixSdkmsRestApi);
  }
}(this, function(expect, FortanixSdkmsRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UnwrapKeyRequestEx', function() {
    it('should create an instance of UnwrapKeyRequestEx', function() {
      // uncomment below and update the code to test UnwrapKeyRequestEx
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be.a(FortanixSdkmsRestApi.UnwrapKeyRequestEx);
    });

    it('should have the property key (base name: "key")', function() {
      // uncomment below and update the code to test the property key
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property alg (base name: "alg")', function() {
      // uncomment below and update the code to test the property alg
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property groupId (base name: "group_id")', function() {
      // uncomment below and update the code to test the property groupId
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property objType (base name: "obj_type")', function() {
      // uncomment below and update the code to test the property objType
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property wrappedKey (base name: "wrapped_key")', function() {
      // uncomment below and update the code to test the property wrappedKey
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property mode (base name: "mode")', function() {
      // uncomment below and update the code to test the property mode
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property iv (base name: "iv")', function() {
      // uncomment below and update the code to test the property iv
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property ad (base name: "ad")', function() {
      // uncomment below and update the code to test the property ad
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property tag (base name: "tag")', function() {
      // uncomment below and update the code to test the property tag
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property keyOps (base name: "key_ops")', function() {
      // uncomment below and update the code to test the property keyOps
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property customMetadata (base name: "custom_metadata")', function() {
      // uncomment below and update the code to test the property customMetadata
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

    it('should have the property rsa (base name: "rsa")', function() {
      // uncomment below and update the code to test the property rsa
      //var instane = new FortanixSdkmsRestApi.UnwrapKeyRequestEx();
      //expect(instance).to.be();
    });

  });

}));
