/**
 * Fortanix SDKMS REST API
 * This is a set of REST APIs for accessing the Fortanix Self-Defending Key Management System. This includes APIs for managing accounts, and for performing cryptographic and key management operations. 
 *
 * OpenAPI spec version: 1.0.0-20181004
 * Contact: support@fortanix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FortanixSdkmsRestApi);
  }
}(this, function(expect, FortanixSdkmsRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FortanixSdkmsRestApi.User();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('User', function() {
    it('should create an instance of User', function() {
      // uncomment below and update the code to test User
      //var instane = new FortanixSdkmsRestApi.User();
      //expect(instance).to.be.a(FortanixSdkmsRestApi.User);
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instane = new FortanixSdkmsRestApi.User();
      //expect(instance).to.be();
    });

    it('should have the property userEmail (base name: "user_email")', function() {
      // uncomment below and update the code to test the property userEmail
      //var instane = new FortanixSdkmsRestApi.User();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new FortanixSdkmsRestApi.User();
      //expect(instance).to.be();
    });

    it('should have the property accountRole (base name: "account_role")', function() {
      // uncomment below and update the code to test the property accountRole
      //var instane = new FortanixSdkmsRestApi.User();
      //expect(instance).to.be();
    });

    it('should have the property groups (base name: "groups")', function() {
      // uncomment below and update the code to test the property groups
      //var instane = new FortanixSdkmsRestApi.User();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instane = new FortanixSdkmsRestApi.User();
      //expect(instance).to.be();
    });

    it('should have the property emailVerified (base name: "email_verified")', function() {
      // uncomment below and update the code to test the property emailVerified
      //var instane = new FortanixSdkmsRestApi.User();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new FortanixSdkmsRestApi.User();
      //expect(instance).to.be();
    });

    it('should have the property lastLoggedInAt (base name: "last_logged_in_at")', function() {
      // uncomment below and update the code to test the property lastLoggedInAt
      //var instane = new FortanixSdkmsRestApi.User();
      //expect(instance).to.be();
    });

    it('should have the property u2fDevices (base name: "u2f_devices")', function() {
      // uncomment below and update the code to test the property u2fDevices
      //var instane = new FortanixSdkmsRestApi.User();
      //expect(instance).to.be();
    });

  });

}));
