/**
 * Fortanix SDKMS REST API
 * This is a set of REST APIs for accessing the Fortanix Self-Defending Key Management System. This includes APIs for managing accounts, and for performing cryptographic and key management operations. 
 *
 * OpenAPI spec version: 1.0.0-20181004
 * Contact: support@fortanix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DigestAlgorithm'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DigestAlgorithm'));
  } else {
    // Browser globals (root is window)
    if (!root.FortanixSdkmsRestApi) {
      root.FortanixSdkmsRestApi = {};
    }
    root.FortanixSdkmsRestApi.MacVerifyRequest = factory(root.FortanixSdkmsRestApi.ApiClient, root.FortanixSdkmsRestApi.DigestAlgorithm);
  }
}(this, function(ApiClient, DigestAlgorithm) {
  'use strict';




  /**
   * The MacVerifyRequest model module.
   * @module model/MacVerifyRequest
   * @version 1.0.0-20181004
   */

  /**
   * Constructs a new <code>MacVerifyRequest</code>.
   * @alias module:model/MacVerifyRequest
   * @class
   * @param alg {module:model/DigestAlgorithm} 
   * @param data {Blob} The data to verify the MAC of.
   */
  var exports = function(alg, data) {
    var _this = this;

    _this['alg'] = alg;
    _this['data'] = data;


  };

  /**
   * Constructs a <code>MacVerifyRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MacVerifyRequest} obj Optional instance to populate.
   * @return {module:model/MacVerifyRequest} The populated <code>MacVerifyRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('alg')) {
        obj['alg'] = DigestAlgorithm.constructFromObject(data['alg']);
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], 'Blob');
      }
      if (data.hasOwnProperty('digest')) {
        obj['digest'] = ApiClient.convertToType(data['digest'], 'Blob');
      }
      if (data.hasOwnProperty('mac')) {
        obj['mac'] = ApiClient.convertToType(data['mac'], 'Blob');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DigestAlgorithm} alg
   */
  exports.prototype['alg'] = undefined;
  /**
   * The data to verify the MAC of.
   * @member {Blob} data
   */
  exports.prototype['data'] = undefined;
  /**
   * The MAC previously computed for the input data. NOTE - this field is deprecated. Instead you should use mac field.
   * @member {Blob} digest
   */
  exports.prototype['digest'] = undefined;
  /**
   * The MAC previously computed for the input data.
   * @member {Blob} mac
   */
  exports.prototype['mac'] = undefined;



  return exports;
}));


