/**
 * Fortanix SDKMS REST API
 * This is a set of REST APIs for accessing the Fortanix Self-Defending Key Management System. This includes APIs for managing accounts, and for performing cryptographic and key management operations. 
 *
 * OpenAPI spec version: 1.0.0-20181004
 * Contact: support@fortanix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FortanixSdkmsRestApi) {
      root.FortanixSdkmsRestApi = {};
    }
    root.FortanixSdkmsRestApi.ObjectType = factory(root.FortanixSdkmsRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class ObjectType.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "AES"
     * @const
     */
    "AES": "AES",
    /**
     * value: "DES"
     * @const
     */
    "DES": "DES",
    /**
     * value: "DES3"
     * @const
     */
    "DES3": "DES3",
    /**
     * value: "RSA"
     * @const
     */
    "RSA": "RSA",
    /**
     * value: "EC"
     * @const
     */
    "EC": "EC",
    /**
     * value: "OPAQUE"
     * @const
     */
    "OPAQUE": "OPAQUE",
    /**
     * value: "HMAC"
     * @const
     */
    "HMAC": "HMAC",
    /**
     * value: "SECRET"
     * @const
     */
    "SECRET": "SECRET",
    /**
     * value: "CERTIFICATE"
     * @const
     */
    "CERTIFICATE": "CERTIFICATE"  };

  /**
   * Returns a <code>ObjectType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/ObjectType} The enum <code>ObjectType</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


