/**
 * Fortanix SDKMS REST API
 * This is a set of REST APIs for accessing the Fortanix Self-Defending Key Management System. This includes APIs for managing accounts, and for performing cryptographic and key management operations. 
 *
 * OpenAPI spec version: 1.0.0-20181004
 * Contact: support@fortanix.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DigestAlgorithm', 'model/SignatureMode', 'model/SobjectDescriptor'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DigestAlgorithm'), require('./SignatureMode'), require('./SobjectDescriptor'));
  } else {
    // Browser globals (root is window)
    if (!root.FortanixSdkmsRestApi) {
      root.FortanixSdkmsRestApi = {};
    }
    root.FortanixSdkmsRestApi.SignRequestEx = factory(root.FortanixSdkmsRestApi.ApiClient, root.FortanixSdkmsRestApi.DigestAlgorithm, root.FortanixSdkmsRestApi.SignatureMode, root.FortanixSdkmsRestApi.SobjectDescriptor);
  }
}(this, function(ApiClient, DigestAlgorithm, SignatureMode, SobjectDescriptor) {
  'use strict';




  /**
   * The SignRequestEx model module.
   * @module model/SignRequestEx
   * @version 1.0.0-20181004
   */

  /**
   * Constructs a new <code>SignRequestEx</code>.
   * @alias module:model/SignRequestEx
   * @class
   * @param key {module:model/SobjectDescriptor} 
   * @param hashAlg {module:model/DigestAlgorithm} 
   */
  var exports = function(key, hashAlg) {
    var _this = this;

    _this['key'] = key;
    _this['hash_alg'] = hashAlg;



  };

  /**
   * Constructs a <code>SignRequestEx</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SignRequestEx} obj Optional instance to populate.
   * @return {module:model/SignRequestEx} The populated <code>SignRequestEx</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('key')) {
        obj['key'] = SobjectDescriptor.constructFromObject(data['key']);
      }
      if (data.hasOwnProperty('hash_alg')) {
        obj['hash_alg'] = DigestAlgorithm.constructFromObject(data['hash_alg']);
      }
      if (data.hasOwnProperty('hash')) {
        obj['hash'] = ApiClient.convertToType(data['hash'], 'Blob');
      }
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], 'Blob');
      }
      if (data.hasOwnProperty('mode')) {
        obj['mode'] = SignatureMode.constructFromObject(data['mode']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SobjectDescriptor} key
   */
  exports.prototype['key'] = undefined;
  /**
   * @member {module:model/DigestAlgorithm} hash_alg
   */
  exports.prototype['hash_alg'] = undefined;
  /**
   * Hash of the data to be signed. Exactly one of `hash` and `data` is required. 
   * @member {Blob} hash
   */
  exports.prototype['hash'] = undefined;
  /**
   * Data to be signed. Exactly one of `hash` and `data` is required. To reduce request size and avoid reaching the request size limit, prefer `hash`. 
   * @member {Blob} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {module:model/SignatureMode} mode
   */
  exports.prototype['mode'] = undefined;



  return exports;
}));


